# Generated by Django 6.0.3 on 2026-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('placements', 'Placements'), ('projects', 'Projects'), ('internship', 'Internship'), ('technical', 'Technical')], default='general', max_length=20),
        ),
    ]
