# Generated by Django 6.0.3 on 2026-03-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='continuity_form',
            field=models.FileField(blank=True, null=True, upload_to='continuity_forms/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
